name: Bumblebee
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Vale
        uses: errata-ai/vale-action@v1.4.0
        with:
          files: __onlyModified
          onlyAnnotateModifiedLines: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
          folder-path: 'docs'
          use-quiet-mode: 'yes'
          check-modified-files-only: 'yes'
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Markdown Lint Check
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .markdownlint.yaml
          debug: true
          search_paths: |
            docs/
            README.md